### ISSUE TITLE
About the pred.py file

### ISSUE THREAD

**Issue by levishen** [policeme/transformer-pointer-generator#11]
I want to predict , so I use the file.
Add the code for this file 
` model_dir = "../mypath/checkpoint"                           
vocab_file = "../mypath/vocab"                             
pred = Prediction(model_dir, vocab_file)                             
content = "2014年，51信用卡管家跟宜信等P2P公司合作，推出线上信贷产品“瞬时贷”，其是一种纯在线操作的信贷模式。51信用卡管家创始人孙海涛说，51目前每天放贷1000万，预计2015年，自营产品加上瞬>时贷，放贷额度将远超30亿"  
    print(pred.predict(content))`

But it give a error `ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.`
So look forward to  your answer. 
Thx

**Comment by levishen** [comment]
I guss shor of  input_y in the file, but I cant correct it.

**Comment by xiongma** [comment]
It's my fault, After changed model structure, I didn't modify the pred.py, Now, I fixed it, please, pull code again.
