### ISSUE TITLE
About Model Figure?

### ISSUE THREAD

**Issue by yjyGo** [policeme/transformer-pointer-generator#12]
@policeme Hi，In the model figure,
1.Multi-head Attention Distribution part: 
what's '1 2 3 ... k-2 k-1 k'? Do they represent different head attention？
2.Final Distribution: Why is Vocabulary distribution on top, copy distribution below?

**Comment by xiongma** [comment]
1. first question, I don't understand u question, for my opinion, different head attention means different feature, in the attention final, we concat them.
2. second question, I don't understand, first, I don't concat the vocabulary distribution and attention, just add them by vocab index.

**Comment by yjyGo** [comment]
![image](https://user-images.githubusercontent.com/39528655/61458660-a255c380-a99d-11e9-8de6-547947e66031.png)

**Comment by yjyGo** [comment]
@policeme look the picture above, especially the content of red circle, you will understand my questions.

**Comment by xiongma** [comment]
not concat.just add. See function final_dist


from Alimail iPhone
 ------------------Original Mail ------------------

**Comment by yjyGo** [comment]
can I add you wechat number?

**Comment by yjyGo** [comment]
我的意思是你的最终分布图形里边蓝色在上，红色在下，蓝色表示词汇表分布，红色代表拷贝分布，我可不可以把它颠倒过来，红在下蓝在上，只是单纯的画图而已。

**Comment by xiongma** [comment]
只是简单的画图，实际是想加，可以看代码，一步步调试，你就会知道。


from Alimail iPhone
 ------------------Original Mail ------------------

**Comment by yjyGo** [comment]
多头注意力分布图形的每个数字表示什么

**Comment by yjyGo** [comment]
我知道相加，论文里也有，你没明白我的意思

**Comment by xiongma** [comment]
详细请阅读 All Attention Is You Need


from Alimail iPhone
 ------------------Original Mail ------------------

**Comment by xiongma** [comment]
你没描述清楚，请详细描述问题


from Alimail iPhone
 ------------------Original Mail ------------------

**Comment by yjyGo** [comment]
你直接回答我截图里面的那些1,2,3，...,k是不是表示第几个头

**Comment by xiongma** [comment]
不是，下次问的时候请阅读代码后提问

**Comment by yjyGo** [comment]
不好意思，言语上表达不清楚很抱歉，可以加微信吗？方便交流。
