### ISSUE TITLE
About inference phase details

### ISSUE THREAD

**Issue by levishen** [policeme/transformer-pointer-generator#16]
`if tf.reduce_sum(y_hat, 1) == x: break`
In model.py 264 lines.
y_hat is [batch_size, seq_length] tensor, 
why tf.reduce_sum(y_hat, 1) can equal to 《pad》 id？
For example, y_hat =[[1,2,3,4,5],[3,4,2,3,6],[2,3,4,5,6]]
tf.reduce_sum(y_hat, 1) = [15,18,20]
But, self.token2idx["<pad>"] just only one number.

**Comment by xiongma** [comment]
this is unuseful code, I will delete it
