### ISSUE TITLE
Run on an English dataset

### ISSUE THREAD

**Issue by Simons2017** [policeme/transformer-pointer-generator#17]
When I run this code on an English dataset, since the length of the English string is counted by characters, the parameter **maxlen** must be set to a very large number. This leads to out of memory. Do you know how to solve this problem?

**Comment by xiongma** [comment]
may be you can try word level

**Comment by Simons2017** [comment]
> may be you can try word level

突然发现同是中国人，直接用中文说了。就是我改了data_load.py ，在第62,63行如果按词数作为判断条件，train的时候会导致ValueError: `generator` yielded an element of shape (114,) where an element of shape (100,) was expected.（maxlen2设为100）。然后我觉得问题出在第138-147行，这里调用的 _generator_fn()生成的sent2还是字符串，计数的时候还是按字符计数，我就不知道该改哪里了，您有什么想法吗？

**Comment by policeme** [comment]
传入_generator_fn的字符串是经过utf-8编码的，传入到方法以后，再进行解码

**Comment by xiongma** [comment]
你传入的字符串长度大于了你在dataset所期望的字符串长度，你要改maxlen2的大小
![image](https://user-images.githubusercontent.com/30991932/63506522-47693c00-c508-11e9-81b8-9868cbd57d9a.png)

**Comment by ronnyli** [comment]
Hi, I'm also using an English dataset. @Simons2017 could you share what changes you had to make to get the code to work? I'm getting an `OutOfRangeError: End of sequence` error which is probably related to this issue
