### ISSUE TITLE
还是在英文数据集上运行的问题

### ISSUE THREAD

**Issue by Simons2017** [policeme/transformer-pointer-generator#18]
我改了data_load.py里的_load_data()，在62,63行以词数作为判断条件，在train的时候，提示ValueError: `generator` yielded an element of shape (114,) where an element of shape (100,) was expected（maxlen2设为了100）.然后我觉得问题出在了_input_fn里的143-147行，这里的_generator_fn()生成的sents2是tf.string的还是以字符计数，然后我就不知道怎么改了，你有什么建议吗，谢谢！

**Comment by xiongma** [comment]
在上个回复中已经说了，模型期待yeild出来的最大字符串长度为100，而你yeild出来的为114，这个肯定要报错
