### ISSUE TITLE
About a new problem using this nice code

### ISSUE THREAD

**Issue by ha-lins** [policeme/transformer-pointer-generator#19]
Hi, @policeme 

Thanks for your fancy code! Your code is helpful to my recent project, which needs two source inputs(X1 and X2). I need the transformer to attend on two sources, while i only want to copy from source X1. What's your opinion about this? 

A possible solution is that i use two encoders and one decoder. I only feed the encoder outputs of X1 into the last layer of the decoder, otherwise i feed the concatenation outputs of two  encoders for joint attention. Do you think it can work well ? Anything wrong with the solution? 

Looking forward to your insightful opinion!

**Comment by xiongma** [comment]
while i only want to copy from source X1, I don't understand the i.

**Comment by ha-lins** [comment]
sorry, 'i' should be 'I'.  I only want the copy mechanism from X1
