### ISSUE TITLE
Baseline on the CNN/DailyMail dataset

### ISSUE THREAD

**Issue by ronnyli** [policeme/transformer-pointer-generator#21]
Hi, thanks for writing this code! I had an idea for the README and wanted to share with you.

I think the tutorial on the README could be even more useful if it included your code's ROUGE score on the [CNN/DailyMail dataset](http://nlpprogress.com/english/summarization.html) which is the standard for comparing English text summarization models. I've been reading several papers ([example 1](https://arxiv.org/pdf/1704.04368.pdf) [example 2](http://web.stanford.edu/class/cs224n/reports/custom/15784595.pdf)) on the topic and they all test out their models on this dataset.

In addition, it would be very helpful to include a tutorial on how to run this code on the CNN/DailyMail dataset since I believe the current code is based on Chinese text.

I am willing to help on this issue if you'd like!

**Comment by xiongma** [comment]
Soory. The work is too busy. I don't have time to do this. If I finish my project. I will complete it. Thanks for u advice


from Alimail iPhone
 ------------------Original Mail ------------------

**Comment by xiongma** [comment]
if u want. U can put a pull request.


from Alimail iPhone
 ------------------Original Mail ------------------

**Comment by ronnyli** [comment]
Thanks for the fast response! I will try to make a pull request :)
