### ISSUE TITLE
Does not use GPU

### ISSUE THREAD

**Issue by ronnyli** [policeme/transformer-pointer-generator#22]
(Hopefully this isn't an error on my side)

I noticed that `requirements.txt` only contains `tensorflow==1.12.0` not `tensorflow-gpu==1.12.0`. Does this mean that the `--gpu_nums` argument for `train.py` doesn't do anything?

Thanks for your help!

**Comment by xiongma** [comment]
sorry, it my fault, it could be tensorflow-gpu==1.12.0 I will repeat it quickly


Cally Ma (马雄)
Chongqing University of Post and Telecommunications
Mobile: +86 15025700935
E-mail: mx15025700935@aliyun.com




------------------------------------------------------------------
发件人：ronnyli <notifications@github.com>
发送时间：2019年9月16日(星期一) 05:53
收件人：policeme/transformer-pointer-generator <transformer-pointer-generator@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[policeme/transformer-pointer-generator] Does not use GPU (#22)

(Hopefully this isn't an error on my side)
I noticed that requirements.txt only contains tensorflow==1.12.0 not tensorflow-gpu==1.12.0. Does this mean that the --gpu_nums argument for train.py doesn't do anything?
Thanks for your help!
