### ISSUE TITLE
Tensor shape for decoder?

### ISSUE THREAD

**Issue by Wanghn95** [policeme/transformer-pointer-generator#25]
Hi policeme, thank you for sharing the code, it's a great work!
And I have some questions for coding:
1. In your work, the tensor shape is confused, I think the shape (N, T1orT2, d_model) is equal to the model shape (batch_size, max_encoder_step or max_decoder_step, embedding_size) ?
2. When the model in decode stage, I cannot understand the ys, also, what's the shape of self.decoder_inputs?
I'm sorry to bother you, but I really your opinions! 
thanks!

**Comment by xiongma** [comment]
the model based on transformer model, I think you should read the transformer paper
