### ISSUE TITLE
你好，如何给transformer加上Coverage Mechanism机制呢，有没有好的实现？

### ISSUE THREAD

**Issue by BlueFishDream** [policeme/transformer-pointer-generator#27]

**Comment by xiongma** [comment]
这个不是我主要的工作，我没有尝试过这个，不好意思

**Comment by BlueFishDream** [comment]
好的，谢谢！&nbsp;

顺祝时祺！


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Cally"<notifications@github.com&gt;; 
发送时间: 2019年11月26日(星期二) 晚上8:44
收件人: "policeme/transformer-pointer-generator"<transformer-pointer-generator@noreply.github.com&gt;; 
抄送: "zjyDream"<975669552@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [policeme/transformer-pointer-generator] 你好，如何给transformer加上Coverage Mechanism机制呢，有没有好的实现？ (#27)




这个不是我主要的工作，我没有尝试过这个，不好意思
