### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'gpu_list'

### ISSUE THREAD

**Issue by niliusha123** [policeme/transformer-pointer-generator#3]
hello，我从群里来到这里的，跑你的代码出现下面的错误，该怎么办，在服务器上跑的程序，GPU只能用一块，谢谢！刚开始学，求解答
完整的错误

- INFO:root:# hparams
INFO:root:# Prepare train/eval batches
INFO:root:# init data
INFO:root:# Load model
Traceback (most recent call last):
  File "train.py", line 54, in <module>
    loss, train_op, global_step, train_summaries = m.train_multi_gpu(xs, ys)
  File "/home/jiang.li/transformer-pointer-generator/model.py", line 220, in train_multi_gpu
    for i, no in enumerate(self.hp.gpu_list):
AttributeError: 'Namespace' object has no attribute 'gpu_list'

**Comment by xiongma** [comment]
Sorry, this is a bug, I will fix it immediately?

**Comment by xiongma** [comment]
Hi, I am so sorry to let wait for long time, my code was just fixed, just pull the new code! thx for star my project!

**Comment by niliusha123** [comment]
好的，谢谢，我再试试
