### ISSUE TITLE
alternative way to download the dataset

### ISSUE THREAD

**Issue by ronsoohyeong** [policeme/transformer-pointer-generator#32]
Hi,
I have been trying to download the dataset, but it requires Baidu netdisk, which I fail to register being outside China. (It says "暂不支持海外及港澳台地区注册")
Can you please give another way to download the dataset?

Best regards,
Ron

**Comment by xiongma** [comment]
sorry, because of the epidemic, we can't use vpn, we just can upload the dataset to domestic, if the vpn it works, I will send it to google drive
