### ISSUE TITLE
training & testing

### ISSUE THREAD

**Issue by cy163** [policeme/transformer-pointer-generator#33]
Q1: In you instruction, only training procedure is discribed, which contains two steps:  STEP 1. download the dataset, and ,STEP 2. Run "python train.py". I wonder how to  test the trained model with a new text. After I feed the system a new text,  as  expected,  it can output a condensed short text. What are the input and output interfaces for use to exchange data with the software .

Q2: I tried to  test the project by running "python train.py". However I failed due to the limited 6G memory on my PC. Hence, I wonder  which parameters can be reset to allow the project to run successfully on a common PC.

**Comment by xiongma** [comment]
to predict the model, you should run the predict.py
