### ISSUE TITLE
what is the meaning of _calc_final_dist() method of model.py?

### ISSUE THREAD

**Issue by yjyGo** [policeme/transformer-pointer-generator#7]
Sorry, but I can't understand about the _calc_finale_dists method, although I tried to made a lot modification, but always get the loss nan. Could you help me for some problems?
First problem: the variable 'attn_dists' has three dimensions, first is batch size, second is ?, third is target sentence length? And what's the element of attn_dists? 
Second: what is dec variable desire ? what is the x variable desire?
Third: using tf.map_fn method in order to put attn_dists's element (according their index:x) into the big three dimensions arrays?
Four: what's the element type of final_dists? integer or float(probability)

**Comment by policeme** [comment]
first question: second is target sentence length or it can say as timestep, just like this [batch_size, timestep, timestep], the element of attn_dists is Vanilla attention before multiply V.
second question: can u write more detail about this question, thx
third question:  yes
fourth: probability, shape [batch_size, timestep, vocab_size],  every element is the probability of vocab.

**Comment by xiongma** [comment]
first question: second is target sentence length or it can say as timestep, just like this [batch_size, timestep, timestep], the element of attn_dists is attention of every time_step for every sample in this batch.
second question: can u write more detail about this question, thx
third question: yes
fourth: probability, shape [batch_size, timestep, vocab_size], every element is the probability of vocab.

**Comment by yjyGo** [comment]
@policeme  First, thank you so much for writing the nice coding. I want to add embedding matrix (obtained from vgae-variational graph auto encoder model) into attn_dists variable, but is hard, it cost me two weeks, I failed to get a good result finally). So I want to understand _calc_final_dist method deeply. Sorry to disturb you again,
In the first question I ever asked you，I ever printed the shape about "attn_dists", but just get (?.?,?), and then I found the third dimension of attn_dists is source sequence length (When I ran program, I found from the error messages), maybe "attn_dists" shape is (batch_size, time_step, source sequence length).
In the fourth question: I made some changes, and found sometimes attn_dist_projected variable's second dimension("dec_t") was 4330 larger than max_len,  vocab_dists's sencond dimesion is 4331, they should all be time_step yes ? Why not is time_step?

**Comment by yjyGo** [comment]
@policeme In the second question,  I just want to know why you modify dec_t's dimensions and x's dimensions in the _calc_final_dist(), you extend their's dimension in order to get the attn_dist_projected variable?

**Comment by xiongma** [comment]
for calc final dist, the x contain vocab index in vocab dict, the atten_dists contain probability of vocab, but in atten_dists, the index of probability is index of timestep, it should be index of vocab, so it should map to vocab probability into the vocab dict, like the [https://github.com/policeme/transformer-pointer-generator/blob/a9d113dec58dc6a2871f2fa8929feaabdc6c5017/model.py#L113](before calc final dist of vocab ),  so I use x to get the true index of vocab. u should this paper[https://arxiv.org/abs/1704.04368](Pointer) to understand deeper

**Comment by xiongma** [comment]
yes, the attn_dists shape is (batch_size, time_step, source sequence length).
for the fourth question, I think it should be max_len, because, in data_load, if the length of source, or length of abstract greater than maxlen1 or maxlen2, I will drop it. so, I think, the error could be from your code, check you code.
