### ISSUE TITLE
About reading data way!

### ISSUE THREAD

**Issue by levishen** [policeme/transformer-pointer-generator#8]
Why use the API "tf.data.Iterator.from_string_handle", but not "tf.data.Iterator.from_structure"?Could you give a reason?

**Comment by policeme** [comment]
this is a good question
1. tf.data.Iterator.from_string_handle has more flexible than tf.data.Iterator.from_structure, when model gets data, just use different handles, it can get data from training data or validation data, just like I wrote.
2. when we use training dataset to train model, we don't want initialize dataset every steps, just initialize once is enough, but tf.data.Iterator.from_structure will initialize data every steps, and  if you use tf.data.Iterator.from_string_handle.make_one_shot_iterator() it will initialize data once. if you use tf.data.Iterator.from_string_handle.make_initializable_iterator(), it will initialize every steps, but you should run`sess.run(val_iter.initializer) # initial val dataset` first.

**Comment by xiongma** [comment]
so, it more flexible

**Comment by policeme** [comment]
this is a good question

tf.data.Iterator.from_string_handle has more flexible than tf.data.Iterator.from_structure
1. when model gets data, just use different handles, it can get data from training data or validation data, just like I wrote.
2. **when we use training dataset to train model, we don't want initialize dataset, when change the source of data, just initialize once is enough.**

**Comment by xiongma** [comment]
this is a good question

tf.data.Iterator.from_string_handle has more flexible than tf.data.Iterator.from_structure

1. when model gets data, just use different handles, it can get data from training data or validation data, just like I wrote.
2. when we use training dataset to train model, we don't want initialize dataset when change the source of data, just initialize once is enough.

**Comment by levishen** [comment]
Thx for your answer.But tf.data.Iterator.from_string_handle need more bigger RAM memory on same data.
