### ISSUE TITLE
question about coverage mechanism

### ISSUE THREAD

**Issue by AbnerCode** [policeme/transformer-pointer-generator#9]
hi, thanks to your code. I have a question:
you say that the Coverage mechanism doesn't suit short summary, so you didn't use this mechanism, just use the first one.

I want to know the reasons or some related papers. Thanks!

**Comment by xiongma** [comment]
I don't have some related papers, I just know from some blog, a lot of blogs say, it didn't suit short summary, so I didn't try, if u tried, and have a good result, hope u can tell me.

**Comment by AbnerCode** [comment]
ok, thx! I run your code in the mutil-GPUs, but the evaluation that is not
exact. Is there something I need to modify?

Cally <notifications@github.com> 于2019年7月11日周四 下午3:47写道：

**Comment by xiongma** [comment]
It's not my domain work, u can try

AbnerCode <notifications@github.com> 于2019年7月11日周四 下午3:50写道：
